# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170715_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_description', models.CharField(max_length=550)),
            ],
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='crs',
            new_name='course',
        ),
    ]
