# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20170722_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(related_name='Courses', to='student.Subject'),
        ),
    ]
