# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20170803_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('Position', models.CharField(max_length=150)),
                ('Bio', models.TextField(max_length=550)),
            ],
        ),
    ]
