# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentform',
            new_name='faculty',
        ),
    ]
