# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20170805_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='fac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('Position', models.CharField(max_length=150)),
                ('Bio', models.TextField(max_length=550)),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='course',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
