# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20170805_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('b_day', models.DateTimeField()),
                ('course', models.ManyToManyField(related_name='Detail', to='student.Course')),
            ],
        ),
        migrations.DeleteModel(
            name='fac',
        ),
    ]
